---
title: "Repaso"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    code_download: true
    theme: cosmo
    highlight: textmate
---

# Introducción

## Ejemplo 1: variable categórica

```{r}
library(rio)
peru21 = import("PER_2021_LAPOP_AmericasBarometer_v1.2_w.dta")
```

```{r}
peru23 = import("bases/PER_2023_LAPOP_AmericasBarometer_v1.0_w.sav")
```

## Describir una variable categórica

```{r}
library(tidyverse)
peru = peru |>
  mutate(ing4rec=recode(ing4, '5' = '1', '6' = '1', '7' = '1',  .default = '0'))
```

```{r}
table(peru$ing4)
table(peru$ing4rec)
```

```{r}
peru = peru |>
  mutate(ing4rec = factor(ing4rec, labels=c("No", "Sí")))
```

```{r}
tabla4 = peru |>
  filter(ing4rec == "No" | ing4rec == "Sí") |>
  count(apoyo = ing4rec, name="Frecuencia") |>
  mutate(Porcentaje = (Frecuencia / sum(Frecuencia)*100 ))
tabla4
```

## Graficar una variable categórica

```{r}
graf8 = ggplot(tabla4, aes(y=Porcentaje, x=apoyo))+
  geom_bar(stat="identity", width=0.5)
graf8
```

## Comparando proporciones

```{r}
peru = peru |>
  mutate(sexo=recode(q1tb, '1' = '1', '2' = '2', '3' = '2')) |>
  mutate(sexo = factor(sexo, labels=c("Hombre", "Mujer/Otro")))
```

```{r}
tabla5 = peru |>
  filter(ing4rec == "No" | ing4rec == "Sí") |> 
  group_by(sexo) |>
  count(Apoyo = ing4rec, name="N")|>
  mutate(total = sum(N), 
         Por = N / total * 100, 
         err = sqrt(Por*(100-Por)/N), 
         liminf = Por - 1.96*err, 
         limsup = Por + 1.96*err)
tabla5
```

## Comparando proporciones gráficamente

```{r}
graf9 = ggplot(tabla5, aes(x=sexo, y=Por, fill=Apoyo))+
  geom_bar(stat="identity", width=0.5)+
  labs(x="Sexo", y="Porcentaje",
       caption="Barómetro de las Américas por LAPOP, 2021")+
  theme_classic()
graf9
```

## Comparando proporciones con intervalos de confianza

```{r}
tabla5 = tabla5[-c(1,3),]
```

```{r}
graf10 = ggplot(tabla5, aes(x=sexo, y=Por))+
  geom_bar(stat="identity")+
  geom_errorbar(aes(ymin=liminf, ymax=limsup), width=0.2)+
  geom_text(aes(label=paste(round(Por, 1))), vjust=-1.5, size=4)+
  labs(x="Sexo", y="Porcentaje",
       caption="Barómetro de las Américas por LAPOP, 2021")+
  theme_classic()
graf10
  
```

## Prueba de significancia para proporciones

```{r}
prop.test(c(803, 759), c(1610,1412))
```
